mod.id = "boathud_extended"
mod.name = "BoatHud Extended"
mod.group = "frn.boathud_extended"
mod.version = "1.2.0"

deps.fabric_loader = "0.19.3"
deps.modmenu = "11.0.4"
deps.cloth = "15.0.140"
loomx.loom_version = "1.17-SNAPSHOT"

["1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
mod.mc_releases = ["1.21.1"]
deps.fabric_api = "0.116.15+1.21.1"

["1.21.4"]
mod.mc_compat = "~1.21.4"
mod.mc_releases = ["1.21.4"]
deps.fabric_api = "0.119.4+1.21.4"
deps.modmenu = "13.0.4"
deps.cloth = "17.0.144"

["1.21.8"]
mod.mc_compat = "~1.21.8"
mod.mc_releases = ["1.21.8"]
deps.fabric_api = "0.136.1+1.21.8"
deps.modmenu = "15.0.2"
deps.cloth = "19.0.147"

["1.21.11"]
mod.mc_compat = "~1.21.11"
mod.mc_releases = ["1.21.11"]
deps.fabric_api = "0.141.6+1.21.11"
deps.modmenu = "17.0.0"
deps.cloth = "21.11.153"

["26.1"]
mod.mc_compat = ">=26.1 <=26.1.2"
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]
deps.fabric_api = "0.155.2+26.1.2"
deps.modmenu = "18.0.0"
deps.cloth = "26.1.154"

["26.2"]
mod.mc_compat = "~26.2"
mod.mc_releases = ["26.2"]
deps.fabric_api = "0.158.0+26.2"
deps.modmenu = "20.0.1"
deps.cloth = "26.2.155"
